from pathlib import Path
import re

path = Path('DimensionGenerator.vb')
text = path.read_text(encoding='utf-8')

if 'DimensionGenerator V0.11' not in text:
    raise RuntimeError('Expected DimensionGenerator V0.11 as patch base')

text = text.replace('DimensionGenerator V0.11', 'DimensionGenerator V0.12')
text = text.replace(
    'V0.11: true reference-member mapping + one global native vertical chain + improved vertical spacing; attachments deferred.',
    'V0.12: collision-aware left/right placement for the global vertical chain; true reference members preserved; attachments deferred.')

old = '''    Dim rightX As Double = view.Left + view.Width
    Dim minY As Double = globalRequest.Anchors.Item(0).SheetPoint.Y
    Dim maxY As Double = globalRequest.Anchors.Item(globalRequest.Anchors.Count - 1).SheetPoint.Y

    globalRequest.PlacementPoint = _
        ThisApplication.TransientGeometry.CreatePoint2d( _
            rightX + 1.35, (minY + maxY) / 2.0)

    globalRequest.OverallPlacementPoint = _
        ThisApplication.TransientGeometry.CreatePoint2d( _
            rightX + 2.55, (minY + maxY) / 2.0)
'''

new = '''    Dim leftX As Double = view.Left
    Dim rightX As Double = view.Left + view.Width
    Dim minY As Double = globalRequest.Anchors.Item(0).SheetPoint.Y
    Dim maxY As Double = globalRequest.Anchors.Item(globalRequest.Anchors.Count - 1).SheetPoint.Y

    ' V0.12: choose the side that cuts the fewest planned horizontal
    ' dimension-extension lines.  Extension length is only a tie-breaker.
    Dim leftCandidateX As Double = leftX - 1.35
    Dim rightCandidateX As Double = rightX + 1.35

    Dim leftCrossings As Integer = 0
    Dim rightCrossings As Integer = 0
    Dim leftTravel As Double = 0
    Dim rightTravel As Double = 0

    Dim leftScore As Double = _
        ScoreVerticalChainSideV012( _
            globalRequest, requests, leftCandidateX, _
            leftCrossings, leftTravel)

    Dim rightScore As Double = _
        ScoreVerticalChainSideV012( _
            globalRequest, requests, rightCandidateX, _
            rightCrossings, rightTravel)

    Dim useLeft As Boolean = leftScore < rightScore
    Dim placementX As Double = If(useLeft, leftCandidateX, rightCandidateX)
    Dim overallX As Double = _
        If(useLeft, leftX - 2.55, rightX + 2.55)

    globalRequest.PlacementPoint = _
        ThisApplication.TransientGeometry.CreatePoint2d( _
            placementX, (minY + maxY) / 2.0)

    globalRequest.OverallPlacementPoint = _
        ThisApplication.TransientGeometry.CreatePoint2d( _
            overallX, (minY + maxY) / 2.0)

    Logger.Info( _
        "VERTICAL_SIDE_CHOICE " & If(useLeft, "LEFT", "RIGHT") & _
        " | leftCrossings=" & leftCrossings.ToString() & _
        " | rightCrossings=" & rightCrossings.ToString() & _
        " | leftTravel_cm=" & Num(leftTravel) & _
        " | rightTravel_cm=" & Num(rightTravel) & _
        " | leftScore=" & Num(leftScore) & _
        " | rightScore=" & Num(rightScore))
'''

if old not in text:
    raise RuntimeError('V0.11 fixed right-side placement block not found')
text = text.replace(old, new, 1)

marker = '''Sub AddVerticalDatumAnchorV011( _
'''
if marker not in text:
    raise RuntimeError('AddVerticalDatumAnchorV011 marker not found')

helpers = r'''
' ===================================================================
' V0.12 COLLISION-AWARE VERTICAL CHAIN SIDE SELECTION
' ===================================================================

Function ScoreVerticalChainSideV012( _
    verticalRequest As AutoChainRequestV01, _
    requests As List(Of AutoChainRequestV01), _
    candidateX As Double, _
    ByRef crossingCount As Integer, _
    ByRef totalTravel As Double) As Double

    crossingCount = 0
    totalTravel = 0

    If verticalRequest Is Nothing OrElse requests Is Nothing Then
        Return Double.MaxValue
    End If

    For Each verticalAnchor As AutoDimAnchorV01 In verticalRequest.Anchors
        If verticalAnchor Is Nothing OrElse verticalAnchor.SheetPoint Is Nothing Then
            Continue For
        End If

        totalTravel += _
            Math.Abs(candidateX - verticalAnchor.SheetPoint.X)

        ' A vertical dimension has a horizontal witness/extension line from
        ' each datum to the vertical dimension line.  Count intersections of
        ' that witness line with the vertical witness lines generated by the
        ' already-planned horizontal dimension chains.
        For Each horizontalRequest As AutoChainRequestV01 In requests
            If horizontalRequest Is Nothing OrElse _
               horizontalRequest.DimensionType <> _
               DimensionTypeEnum.kHorizontalDimensionType Then
                Continue For
            End If

            For Each horizontalAnchor As AutoDimAnchorV01 In horizontalRequest.Anchors
                If horizontalAnchor Is Nothing OrElse _
                   horizontalAnchor.SheetPoint Is Nothing Then
                    Continue For
                End If

                Dim extensionY As Double = _
                    HorizontalExtensionLimitYV012( _
                        horizontalAnchor, horizontalRequest)

                If VerticalWitnessCrossingV012( _
                    verticalAnchor.SheetPoint, _
                    candidateX, _
                    horizontalAnchor.SheetPoint, _
                    extensionY) Then

                    crossingCount += 1
                End If
            Next
        Next
    Next

    ' One actual line crossing is much more objectionable than several cm of
    ' extra witness-line travel.  Travel therefore acts only as a tie-breaker.
    Return crossingCount * 100.0 + totalTravel
End Function


Function HorizontalExtensionLimitYV012( _
    anchor As AutoDimAnchorV01, _
    request As AutoChainRequestV01) As Double

    If anchor Is Nothing OrElse anchor.SheetPoint Is Nothing OrElse _
       request Is Nothing Then Return 0

    Dim y0 As Double = anchor.SheetPoint.Y
    Dim bestY As Double = y0
    Dim bestDistance As Double = 0

    If request.PlacementPoint IsNot Nothing Then
        Dim d As Double = Math.Abs(request.PlacementPoint.Y - y0)
        If d > bestDistance Then
            bestDistance = d
            bestY = request.PlacementPoint.Y
        End If
    End If

    If request.OverallPlacementPoint IsNot Nothing Then
        Dim d As Double = Math.Abs(request.OverallPlacementPoint.Y - y0)
        If d > bestDistance Then
            bestDistance = d
            bestY = request.OverallPlacementPoint.Y
        End If
    End If

    Return bestY
End Function


Function VerticalWitnessCrossingV012( _
    verticalDatum As Point2d, _
    verticalDimensionX As Double, _
    horizontalDatum As Point2d, _
    horizontalExtensionY As Double) As Boolean

    If verticalDatum Is Nothing OrElse horizontalDatum Is Nothing Then
        Return False
    End If

    ' Horizontal witness line belonging to the vertical chain:
    ' (verticalDatum.X, verticalDatum.Y) -> (verticalDimensionX, verticalDatum.Y)
    Dim xMin As Double = Math.Min(verticalDatum.X, verticalDimensionX)
    Dim xMax As Double = Math.Max(verticalDatum.X, verticalDimensionX)

    ' Vertical witness line belonging to a horizontal chain:
    ' (horizontalDatum.X, horizontalDatum.Y) ->
    ' (horizontalDatum.X, horizontalExtensionY)
    Dim yMin As Double = Math.Min(horizontalDatum.Y, horizontalExtensionY)
    Dim yMax As Double = Math.Max(horizontalDatum.Y, horizontalExtensionY)

    ' Small clearance avoids counting a shared endpoint/touch as a visual
    ' crossing.  Inventor drawing database length is cm here.
    Const clearance As Double = 0.03

    If horizontalDatum.X <= xMin + clearance OrElse _
       horizontalDatum.X >= xMax - clearance Then
        Return False
    End If

    If verticalDatum.Y <= yMin + clearance OrElse _
       verticalDatum.Y >= yMax - clearance Then
        Return False
    End If

    Return True
End Function


'''

text = text.replace(marker, helpers + marker, 1)

path.write_text(text, encoding='utf-8')
print('Patched DimensionGenerator.vb to V0.12 collision-aware vertical placement')
