#!/usr/bin/env python3
from pathlib import Path

p = Path('DimensionGenerator.vb')
s = p.read_text(encoding='utf-8')

s = s.replace('DIMENSION GENERATOR V0.6 - SAFE STRAIGHT-COMPONENT AXES + CHAINS',
              'DIMENSION GENERATOR V0.6.1 - CHAINS + EXTERNAL CENTERLINES')
s = s.replace('"DimensionGenerator V0.6"', '"DimensionGenerator V0.6.1"')
s = s.replace('"DimensionGenerator V0.6 failed:"', '"DimensionGenerator V0.6.1 failed:"')

start = s.index('Function ResolveFittingCenterIntentV04(')
end = s.index('\nEnd Function', start) + len('\nEnd Function')

new_func = r'''Function ResolveFittingCenterIntentV04( _
    sheet As Sheet, _
    view As DrawingView, _
    node As NodeRecord, _
    target As Point2d) As GeometryIntent

    ' V0.6.1 PRODUCTION SAFETY
    ' DimensionGenerator NEVER calls AddBisector.
    ' Centerlines are generated separately by CenterlineGenerator.vb and will
    ' be consumed only after that spool-wide centerline pass is verified.
    '
    ' For now centre-dependent dimensions are deferred, while projected-curve
    ' dimensions and native ChainDimensionSet remain enabled and stable.

    If node IsNot Nothing Then
        Logger.Info( _
            "Center-dependent anchor deferred for " & _
            node.Code & "/" & node.ComponentType & _
            " (centerlines generated externally)")
    End If

    Return Nothing
End Function'''

s = s[:start] + new_func + s[end:]

s = s.replace('V0.5.1 stable mode: chains enabled; centerline-dependent and attachment dimensions deferred.',
              'V0.6.1 stable mode: chains enabled; centerlines generated by separate CenterlineGenerator rule.')

p.write_text(s, encoding='utf-8', newline='\n')
print('Patched DimensionGenerator to V0.6.1: no AddBisector in production rule')
